# Generated by Django 6.0 on 2025-12-31 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='銘柄コード')),
                ('name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('sector', models.CharField(blank=True, max_length=50, null=True, verbose_name='業種')),
                ('market', models.CharField(blank=True, max_length=50, null=True, verbose_name='市場')),
                ('description', models.TextField(blank=True, null=True, verbose_name='事業内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='現在株価')),
                ('per', models.FloatField(null=True, verbose_name='PER')),
                ('pbr', models.FloatField(null=True, verbose_name='PBR')),
                ('roe', models.FloatField(null=True, verbose_name='ROE')),
                ('f_score', models.IntegerField(help_text='0-9点。財務健全性', null=True, verbose_name='Piotroski F-Score')),
                ('sloan_ratio', models.FloatField(help_text='利益の質。高いと危険', null=True, verbose_name='Sloan Ratio')),
                ('roic', models.FloatField(help_text='投下資本利益率', null=True, verbose_name='ROIC')),
                ('wacc', models.FloatField(help_text='加重平均資本コスト', null=True, verbose_name='WACC')),
                ('ai_analysis', models.TextField(blank=True, null=True, verbose_name='AI分析コメント')),
                ('ai_score', models.IntegerField(help_text='0-100点', null=True, verbose_name='AI総合スコア')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='stocks.stock')),
            ],
        ),
    ]
