# Generated by Django 5.2.10 on 2026-01-23 14:36

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Falseなら非表示', verbose_name='有効フラグ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='銘柄コード')),
                ('name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('sector', models.CharField(blank=True, max_length=50, null=True, verbose_name='業種')),
                ('market', models.CharField(blank=True, max_length=50, null=True, verbose_name='市場')),
                ('description', models.TextField(blank=True, null=True, verbose_name='事業内容')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Falseなら非表示', verbose_name='有効フラグ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('fiscal_year', models.IntegerField(help_text='例: 2024', verbose_name='決算年度')),
                ('quarter', models.IntegerField(choices=[(1, '第1四半期'), (2, '第2四半期'), (3, '第3四半期'), (4, '通期')], default=4, help_text='通期なら4', verbose_name='四半期')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='決算期末日')),
                ('revenue', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='売上高')),
                ('operating_income', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='営業利益')),
                ('net_income', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='当期純利益')),
                ('ebit', models.DecimalField(decimal_places=0, help_text='利払前・税引前利益', max_digits=20, null=True, verbose_name='EBIT')),
                ('interest_expense', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='支払利息')),
                ('depreciation', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='減価償却費')),
                ('total_assets', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='総資産')),
                ('total_equity', models.DecimalField(decimal_places=0, help_text='旧net_assets', max_digits=20, null=True, verbose_name='純資産(株主資本)')),
                ('current_assets', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='流動資産')),
                ('current_liabilities', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='流動負債')),
                ('long_term_debt', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='長期負債')),
                ('inventory', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='棚卸資産(在庫)')),
                ('retained_earnings', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='利益剰余金')),
                ('operating_cf', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='営業CF')),
                ('investing_cf', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='投資CF')),
                ('financing_cf', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='財務CF')),
                ('capex', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='設備投資(CapEx)')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='stocks.stock')),
            ],
            options={
                'ordering': ['-fiscal_year', '-quarter'],
                'unique_together': {('stock', 'fiscal_year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Falseなら非表示', verbose_name='有効フラグ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('date', models.DateField(auto_now_add=True, verbose_name='分析日')),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='株価')),
                ('market_cap', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='時価総額')),
                ('z_score', models.FloatField(null=True, verbose_name='Altman Z-Score')),
                ('f_score', models.IntegerField(null=True, verbose_name='Piotroski F-Score')),
                ('accruals_ratio', models.FloatField(null=True, verbose_name='Accruals Ratio')),
                ('gross_profitability', models.FloatField(null=True, verbose_name='Gross Profitability')),
                ('roiic', models.FloatField(null=True, verbose_name='ROIIC')),
                ('implied_growth_rate', models.FloatField(null=True, verbose_name='逆算DCF成長率(%)')),
                ('status', models.CharField(default='Hold', help_text='Strong Buy, Sell etc', max_length=20, verbose_name='判定ステータス')),
                ('is_good_buy', models.BooleanField(default=False, verbose_name='買いシグナル')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI分析要約')),
                ('financial_statement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='stocks.financialstatement')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='stocks.stock')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='StockFetchLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Falseなら非表示', verbose_name='有効フラグ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FETCHING', 'Fetching'), ('FAILURE', 'Failure')], max_length=10, verbose_name='ステータス')),
                ('source', models.CharField(default='yfinance', max_length=50, verbose_name='取得元')),
                ('message', models.TextField(blank=True, null=True, verbose_name='ログ詳細')),
                ('error_detail', models.JSONField(blank=True, null=True, verbose_name='エラー詳細JSON')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='stocks.stock')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock', '-created_at'], name='stocks_stoc_stock_i_cc4e07_idx'), models.Index(fields=['created_at', 'status'], name='stocks_stoc_created_79f245_idx')],
            },
        ),
    ]
