# Generated by Django 6.0 on 2026-01-18 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='銘柄コード')),
                ('name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('sector', models.CharField(blank=True, max_length=50, null=True, verbose_name='業種')),
                ('market', models.CharField(blank=True, max_length=50, null=True, verbose_name='市場')),
                ('description', models.TextField(blank=True, null=True, verbose_name='事業内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='例: 2024', verbose_name='決算年度')),
                ('quarter', models.IntegerField(choices=[(1, '第1四半期'), (2, '第2四半期'), (3, '第3四半期'), (4, '通期')], default=4, help_text='通期なら4', verbose_name='四半期')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='決算期末日')),
                ('revenue', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='売上高')),
                ('operating_income', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='営業利益')),
                ('net_income', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='当期純利益')),
                ('ebit', models.DecimalField(decimal_places=0, help_text='利払前・税引前利益', max_digits=20, null=True, verbose_name='EBIT')),
                ('interest_expense', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='支払利息')),
                ('depreciation', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='減価償却費')),
                ('total_assets', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='総資産')),
                ('total_equity', models.DecimalField(decimal_places=0, help_text='旧net_assets', max_digits=20, null=True, verbose_name='純資産(株主資本)')),
                ('current_assets', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='流動資産')),
                ('current_liabilities', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='流動負債')),
                ('long_term_debt', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='長期負債')),
                ('inventory', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='棚卸資産(在庫)')),
                ('retained_earnings', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='利益剰余金')),
                ('operating_cf', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='営業CF')),
                ('investing_cf', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='投資CF')),
                ('financing_cf', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='財務CF')),
                ('capex', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='設備投資(CapEx)')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='stocks.stock')),
            ],
            options={
                'ordering': ['-fiscal_year', '-quarter'],
                'unique_together': {('stock', 'fiscal_year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='分析日')),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='株価')),
                ('market_cap', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='時価総額')),
                ('z_score', models.FloatField(help_text='倒産リスク (3.0以上で安全)', null=True, verbose_name='Altman Z-Score')),
                ('f_score', models.IntegerField(help_text='0-9点 (7点以上で優秀)', null=True, verbose_name='Piotroski F-Score')),
                ('accruals_ratio', models.FloatField(help_text='低いほうが良い (<0.05)', null=True, verbose_name='Accruals Ratio')),
                ('gross_profitability', models.FloatField(help_text='粗利/総資産 (0.33以上で優秀)', null=True, verbose_name='Gross Profitability')),
                ('roiic', models.FloatField(help_text='増分投下資本利益率', null=True, verbose_name='ROIIC')),
                ('implied_growth_rate', models.FloatField(help_text='現在の株価が織り込む成長率', null=True, verbose_name='逆算DCF成長率(%)')),
                ('status', models.CharField(default='Hold', help_text='Strong Buy, Sell etc', max_length=20, verbose_name='判定ステータス')),
                ('is_good_buy', models.BooleanField(default=False, verbose_name='買いシグナル')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI分析要約')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_statement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='stocks.financialstatement')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='stocks.stock')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
