# Generated by Django 6.0 on 2026-01-03 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='例: 2024', verbose_name='決算年度')),
                ('quarter', models.IntegerField(choices=[(1, '第1四半期'), (2, '第2四半期'), (3, '第3四半期'), (4, '通期')], default=4, help_text='通期なら4', verbose_name='四半期')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='決算期末日')),
                ('revenue', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='売上高')),
                ('operating_income', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='営業利益')),
                ('net_income', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='当期純利益')),
                ('total_assets', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='総資産')),
                ('net_assets', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='純資産')),
                ('current_assets', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='流動資産')),
                ('current_liabilities', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='流動負債')),
                ('operating_cf', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='営業CF')),
                ('investing_cf', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='投資CF')),
                ('financing_cf', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='財務CF')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='stocks.stock')),
            ],
            options={
                'ordering': ['-fiscal_year', '-quarter'],
                'unique_together': {('stock', 'fiscal_year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='分析日')),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='株価')),
                ('market_cap', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='時価総額')),
                ('f_score', models.IntegerField(help_text='0-9点', null=True, verbose_name='Piotroski F-Score')),
                ('accruals_ratio', models.FloatField(help_text='低いほうが良い', null=True, verbose_name='Accruals Ratio')),
                ('delta_noa', models.FloatField(help_text='純営業資産の変化率', null=True, verbose_name='ΔNOA')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI分析要約')),
                ('is_good_buy', models.BooleanField(default=False, verbose_name='買いシグナル')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='stocks.stock')),
                ('financial_statement', models.ForeignKey(blank=True, help_text='根拠となった決算データ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.financialstatement')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.DeleteModel(
            name='FinancialIndicator',
        ),
    ]
