# Generated by Django 5.2.10 on 2026-01-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='japanese_market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='japanese_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='japanese_sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
