# Generated by Django 5.2.10 on 2026-01-23 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StockFetchLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FETCHING', 'Fetching'), ('FAILURE', 'Failure')], max_length=10, verbose_name='ステータス')),
                ('source', models.CharField(default='yfinance', max_length=50, verbose_name='取得元')),
                ('message', models.TextField(blank=True, null=True, verbose_name='ログ詳細')),
                ('error_detail', models.JSONField(blank=True, null=True, verbose_name='エラー詳細JSON')),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='実行日時')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='stocks.stock')),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['stock', '-executed_at'], name='stocks_stoc_stock_i_8262bd_idx'), models.Index(fields=['executed_at', 'status'], name='stocks_stoc_execute_247d60_idx')],
            },
        ),
    ]
