# Generated by Django 5.2.10 on 2026-01-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_japanese_market_stock_japanese_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='implied_revenue_growth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
