# Generated by Django 5.2.10 on 2026-01-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_analysisresult_implied_revenue_growth'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='actual_revenue_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='expectation_gap',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
