# Generated by Django 5.2.10 on 2026-01-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_analysisresult_actual_revenue_growth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='expectation_structure',
            field=models.CharField(default='Neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='risk_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='risk_level',
            field=models.CharField(default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='state',
            field=models.CharField(default='Unclear', max_length=50),
        ),
    ]
