# Generated by Django 5.2.10 on 2026-01-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_analysisresult_expectation_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='tag_accounting_risk',
            field=models.BooleanField(default=False, verbose_name='会計リスク'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tag_cash_cow',
            field=models.BooleanField(default=False, verbose_name='キャッシュ製造機'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tag_fragile',
            field=models.BooleanField(default=False, verbose_name='前提崩壊リスク'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tag_high_volatility',
            field=models.BooleanField(default=False, verbose_name='ボラ覚悟'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tag_institutional',
            field=models.BooleanField(default=False, verbose_name='プロ好み'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tag_quality_growth',
            field=models.BooleanField(default=False, verbose_name='クオリティ・グロース'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tag_safety_shield',
            field=models.BooleanField(default=False, verbose_name='盤石の盾'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tag_silent_improver',
            field=models.BooleanField(default=False, verbose_name='静かなる改善'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tag_single_engine',
            field=models.BooleanField(default=False, verbose_name='片肺飛行'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tag_turnaround',
            field=models.BooleanField(default=False, verbose_name='復活の兆し'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tag_zombie',
            field=models.BooleanField(default=False, verbose_name='ゾンビ企業'),
        ),
    ]
