# Generated by Django 5.2.10 on 2026-02-01 00:29

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_analysisresult_tag_accounting_risk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Falseなら非表示', verbose_name='有効フラグ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(default='My Portfolio', max_length=100, verbose_name='ポートフォリオ名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('owner_id', models.CharField(db_index=True, default='guest', max_length=100, verbose_name='所有者ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Falseなら非表示', verbose_name='有効フラグ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='保有株数')),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='平均取得単価')),
                ('target_weight', models.FloatField(blank=True, null=True, verbose_name='目標比率(%)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='投資メモ')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stocks.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='stocks.stock')),
            ],
            options={
                'ordering': ['stock__code'],
                'unique_together': {('portfolio', 'stock')},
            },
        ),
    ]
