# Generated by Django 5.2.10 on 2026-02-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_portfolio_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='exit_strategy',
            field=models.TextField(blank=True, help_text='何が起きたら間違いを認めて損切りするか？（反証可能性の定義）', null=True, verbose_name='撤退条件 (When to Sell?)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='investment_thesis',
            field=models.TextField(blank=True, help_text='なぜこの株を買うのか？どのシナリオに賭けているのか？', null=True, verbose_name='投資仮説 (Why Now?)'),
        ),
    ]
