# Generated by Django 5.2.10 on 2026-02-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_portfolioitem_exit_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='free_cash_flow',
            field=models.DecimalField(decimal_places=0, help_text='営業CF - CapEx', max_digits=20, null=True, verbose_name='フリーCF'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='net_income',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='当期純利益'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='operating_cf',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='営業CF'),
        ),
    ]
