# Generated by Django 5.2.10 on 2026-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_analysisresult_free_cash_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sector_17_code_name',
            field=models.CharField(blank=True, choices=[('IT・通信・サービス', 'IT・通信・サービス'), ('自動車・輸送機', '自動車・輸送機'), ('電気・精密機器', '電気・精密機器'), ('銀行・金融', '銀行・金融'), ('商社・卸売', '商社・卸売'), ('小売・外食', '小売・外食'), ('医薬品・ヘルスケア', '医薬品・ヘルスケア'), ('素材・化学', '素材・化学'), ('機械・建設', '機械・建設'), ('エネルギー・インフラ', 'エネルギー・インフラ'), ('不動産', '不動産'), ('その他', 'その他')], max_length=100, null=True, verbose_name='17業種コード'),
        ),
    ]
