# Generated by Django 5.2.10 on 2026-02-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_stock_sector_17_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='bps',
            field=models.FloatField(help_text='1株当たり純資産', null=True, verbose_name='BPS(円)'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='dividend_yield',
            field=models.FloatField(null=True, verbose_name='配当利回り(%)'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='eps',
            field=models.FloatField(help_text='1株当たり純利益', null=True, verbose_name='EPS(円)'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='equity_ratio',
            field=models.FloatField(null=True, verbose_name='自己資本比率(%)'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='pbr',
            field=models.FloatField(help_text='株価純資産倍率', null=True, verbose_name='PBR(倍)'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='per',
            field=models.FloatField(help_text='株価収益率', null=True, verbose_name='PER(倍)'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='roa',
            field=models.FloatField(help_text='総資産利益率', null=True, verbose_name='ROA(%)'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='roe',
            field=models.FloatField(help_text='自己資本利益率', null=True, verbose_name='ROE(%)'),
        ),
    ]
