# Generated by Django 5.2.10 on 2026-03-08 03:17

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_analysisresult_bps_analysisresult_dividend_yield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='alpha_1month',
            field=models.FloatField(blank=True, help_text='直近1ヶ月の超過リターン(%)', null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='alpha_3month',
            field=models.FloatField(blank=True, help_text='直近3ヶ月の超過リターン(%)', null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='alpha_benchmark',
            field=models.CharField(default='TOPIX', help_text='比較対象(例: TOPIX, 業種別指数)', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='market_cap_percentile',
            field=models.FloatField(blank=True, help_text='上位何%か(例: 5.2)', null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='market_cap_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='market_cap_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='per_sector_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='per_sector_percentile',
            field=models.FloatField(blank=True, help_text='セクター内で割安な方から上位何%か', null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='per_sector_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='per_sector_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='roe_percentile',
            field=models.FloatField(blank=True, help_text='上位何%か', null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='roe_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyStockPrice',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Falseなら非表示', verbose_name='有効フラグ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('date', models.DateField(db_index=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('adjusted_close', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='stocks.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['stock', '-date'], name='stocks_dail_stock_i_13914e_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
