# Generated by Django 5.2.10 on 2026-03-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_analysisresult_alpha_1month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='health_score',
            field=models.FloatField(blank=True, help_text='0〜100の総合評価点', null=True, verbose_name='総合ヘルススコア'),
        ),
    ]
