# Generated by Django 5.2.10 on 2026-04-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_analysisresult_health_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ai_business_summary',
            field=models.TextField(blank=True, null=True, verbose_name='AI事業概要'),
        ),
        migrations.AddField(
            model_name='stock',
            name='ai_profile_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AIプロファイル最終更新日'),
        ),
        migrations.AddField(
            model_name='stock',
            name='ai_strengths',
            field=models.JSONField(blank=True, null=True, verbose_name='AI強み分析'),
        ),
        migrations.AddField(
            model_name='stock',
            name='ai_weaknesses',
            field=models.JSONField(blank=True, null=True, verbose_name='AI課題・弱み分析'),
        ),
    ]
