import os

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-boql^wdgl*m_t=o(c)-n%-$u%unpiu$s)-ztiwhdz$&t#vkmfe"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3003",
    "http://127.0.0.1:3000",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # --- サードパーティ ---
    "corsheaders",  # CORS (Next.jsとの通信用)
    "strawberry.django",  # GraphQL
    # --- 自作アプリ ---
    "stocks",
    "users",
    "mailer",
]

AUTH_USER_MODEL = "users.User"  # これが最重要

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # <--- これを一番上に追加
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # ← 空リスト [] から変更！
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ==========================================
# ロギング設定
# ==========================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        # ターミナルで見やすいシンプルなフォーマット
        "console": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
        },
    },
    "loggers": {
        # "mailer" アプリからのログを拾う
        "mailer": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        # プロジェクト全体（stocksやusersなど）のデフォルト
        "": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("DB_NAME", "db.sqlite3"),
        "USER": os.environ.get("DB_USER", ""),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", ""),
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


LANGUAGE_CODE = "ja"  # 日本語

TIME_ZONE = "Asia/Tokyo"  # JST

USE_I18N = True

USE_TZ = True


# ==========================================
# メール送信設定 (AWS SES / MailMan用)
# ==========================================
# TrueならDjango標準(ローカルでコンソール出力)、Falseならboto3でSESから直接送信
USE_DJANGO_EMAIL = os.environ.get("USE_DJANGO_EMAIL", "True") == "True"

if USE_DJANGO_EMAIL:
    # 開発用：メールを送信せずにターミナルに表示する
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# SMTP用の設定（EMAIL_HOSTなど）は使わないので削除しました。
# 代わりにMailMan(boto3)が使うSES用の認証情報を読み込みます。
AWS_SES_ACCESS_KEY_ID = os.environ.get("AWS_SES_ACCESS_KEY_ID")
AWS_SES_SECRET_ACCESS_KEY = os.environ.get("AWS_SES_SECRET_KEY_ID")
AWS_SES_REGION_NAME = os.environ.get("AWS_SES_REGION", "ap-northeast-1")

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "support@stockmri.com")

# (必要であれば) staging環境で特定のアドレス以外にメールを飛ばさない設定
STAGING_EMAIL_REDIRECT_RECIPIENTS = os.environ.get(
    "STAGING_EMAIL_REDIRECT_RECIPIENTS", ""
).split(",")
