/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "mutation AddToPortfolio($ownerId: String!, $stockCode: String!, $quantity: Float!, $averagePrice: Float!, $investmentThesis: String, $exitStrategy: String) {\n  addToPortfolio(\n    ownerId: $ownerId\n    stockCode: $stockCode\n    quantity: $quantity\n    averagePrice: $averagePrice\n    investmentThesis: $investmentThesis\n    exitStrategy: $exitStrategy\n  ) {\n    id\n    name\n    items {\n      stock {\n        code\n      }\n      quantity\n      investmentThesis\n      exitStrategy\n    }\n  }\n}": typeof types.AddToPortfolioDocument,
    "query GetMyPortfolio($ownerId: String!) {\n  myPortfolio(ownerId: $ownerId) {\n    id\n    name\n    items {\n      stock {\n        code\n        name\n        japaneseName\n        market\n        analysisResults {\n          stockPrice\n          status\n        }\n      }\n      quantity\n      averagePrice\n      currentValue\n      profitLoss\n      investmentThesis\n      exitStrategy\n    }\n    analysis {\n      totalValue\n      healthScore\n      diagnosisSummary\n      categoryExposure\n      tagExposure\n      narrativeAnalysis\n    }\n  }\n}": typeof types.GetMyPortfolioDocument,
    "query GetStockDetail($code: String!) {\n  stock(code: $code) {\n    code\n    name\n    japaneseName\n    market\n    japaneseMarket\n    sector17CodeName\n    description\n    analysisResults {\n      date\n      stockPrice\n      marketCap\n      status\n      aiSummary\n      riskLevel\n      riskDetails\n      state\n      expectationStructure\n      zScore\n      fScore\n      expectationGap\n      impliedRevenueGrowth\n      actualRevenueGrowth\n      tagSafetyShield\n      tagQualityGrowth\n      tagInstitutional\n      tagCashCow\n      tagSingleEngine\n      tagHighVolatility\n      tagSilentImprover\n      tagTurnaround\n      tagZombie\n      tagAccountingRisk\n      tagFragile\n      per\n      pbr\n      roe\n      roa\n      eps\n      bps\n      equityRatio\n      dividendYield\n      freeCashFlow\n    }\n    financials {\n      fiscalYear\n      quarter\n      periodEnd\n      revenue\n      operatingIncome\n      netIncome\n      operatingCf\n      investingCf\n      financingCf\n      totalAssets\n      totalEquity\n    }\n  }\n}": typeof types.GetStockDetailDocument,
    "query GetStocks($search: String, $status: String, $rankingMode: String, $sector: String, $limit: Int, $offset: Int, $sortBy: String, $sortOrder: String) {\n  stocks(\n    search: $search\n    status: $status\n    rankingMode: $rankingMode\n    sector: $sector\n    limit: $limit\n    offset: $offset\n    sortBy: $sortBy\n    sortOrder: $sortOrder\n  ) {\n    code\n    name\n    japaneseName\n    market\n    japaneseMarket\n    sector17CodeName\n    analysisResults {\n      stockPrice\n      status\n      zScore\n      grossProfitability\n      expectationGap\n      per\n      pbr\n      dividendYield\n      roe\n      tagZombie\n      tagSafetyShield\n      tagQualityGrowth\n      tagInstitutional\n      tagCashCow\n      tagSingleEngine\n      tagSilentImprover\n      tagTurnaround\n      tagAccountingRisk\n      tagHighVolatility\n      tagFragile\n      fScore\n      actualRevenueGrowth\n      freeCashFlow\n      operatingCf\n      netIncome\n    }\n  }\n}": typeof types.GetStocksDocument,
    "mutation RemoveFromPortfolio($ownerId: String!, $stockCode: String!) {\n  removeFromPortfolio(ownerId: $ownerId, stockCode: $stockCode) {\n    id\n    analysis {\n      totalValue\n      healthScore\n      narrativeAnalysis\n      diagnosisSummary\n    }\n    items {\n      stock {\n        code\n      }\n    }\n  }\n}": typeof types.RemoveFromPortfolioDocument,
};
const documents: Documents = {
    "mutation AddToPortfolio($ownerId: String!, $stockCode: String!, $quantity: Float!, $averagePrice: Float!, $investmentThesis: String, $exitStrategy: String) {\n  addToPortfolio(\n    ownerId: $ownerId\n    stockCode: $stockCode\n    quantity: $quantity\n    averagePrice: $averagePrice\n    investmentThesis: $investmentThesis\n    exitStrategy: $exitStrategy\n  ) {\n    id\n    name\n    items {\n      stock {\n        code\n      }\n      quantity\n      investmentThesis\n      exitStrategy\n    }\n  }\n}": types.AddToPortfolioDocument,
    "query GetMyPortfolio($ownerId: String!) {\n  myPortfolio(ownerId: $ownerId) {\n    id\n    name\n    items {\n      stock {\n        code\n        name\n        japaneseName\n        market\n        analysisResults {\n          stockPrice\n          status\n        }\n      }\n      quantity\n      averagePrice\n      currentValue\n      profitLoss\n      investmentThesis\n      exitStrategy\n    }\n    analysis {\n      totalValue\n      healthScore\n      diagnosisSummary\n      categoryExposure\n      tagExposure\n      narrativeAnalysis\n    }\n  }\n}": types.GetMyPortfolioDocument,
    "query GetStockDetail($code: String!) {\n  stock(code: $code) {\n    code\n    name\n    japaneseName\n    market\n    japaneseMarket\n    sector17CodeName\n    description\n    analysisResults {\n      date\n      stockPrice\n      marketCap\n      status\n      aiSummary\n      riskLevel\n      riskDetails\n      state\n      expectationStructure\n      zScore\n      fScore\n      expectationGap\n      impliedRevenueGrowth\n      actualRevenueGrowth\n      tagSafetyShield\n      tagQualityGrowth\n      tagInstitutional\n      tagCashCow\n      tagSingleEngine\n      tagHighVolatility\n      tagSilentImprover\n      tagTurnaround\n      tagZombie\n      tagAccountingRisk\n      tagFragile\n      per\n      pbr\n      roe\n      roa\n      eps\n      bps\n      equityRatio\n      dividendYield\n      freeCashFlow\n    }\n    financials {\n      fiscalYear\n      quarter\n      periodEnd\n      revenue\n      operatingIncome\n      netIncome\n      operatingCf\n      investingCf\n      financingCf\n      totalAssets\n      totalEquity\n    }\n  }\n}": types.GetStockDetailDocument,
    "query GetStocks($search: String, $status: String, $rankingMode: String, $sector: String, $limit: Int, $offset: Int, $sortBy: String, $sortOrder: String) {\n  stocks(\n    search: $search\n    status: $status\n    rankingMode: $rankingMode\n    sector: $sector\n    limit: $limit\n    offset: $offset\n    sortBy: $sortBy\n    sortOrder: $sortOrder\n  ) {\n    code\n    name\n    japaneseName\n    market\n    japaneseMarket\n    sector17CodeName\n    analysisResults {\n      stockPrice\n      status\n      zScore\n      grossProfitability\n      expectationGap\n      per\n      pbr\n      dividendYield\n      roe\n      tagZombie\n      tagSafetyShield\n      tagQualityGrowth\n      tagInstitutional\n      tagCashCow\n      tagSingleEngine\n      tagSilentImprover\n      tagTurnaround\n      tagAccountingRisk\n      tagHighVolatility\n      tagFragile\n      fScore\n      actualRevenueGrowth\n      freeCashFlow\n      operatingCf\n      netIncome\n    }\n  }\n}": types.GetStocksDocument,
    "mutation RemoveFromPortfolio($ownerId: String!, $stockCode: String!) {\n  removeFromPortfolio(ownerId: $ownerId, stockCode: $stockCode) {\n    id\n    analysis {\n      totalValue\n      healthScore\n      narrativeAnalysis\n      diagnosisSummary\n    }\n    items {\n      stock {\n        code\n      }\n    }\n  }\n}": types.RemoveFromPortfolioDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation AddToPortfolio($ownerId: String!, $stockCode: String!, $quantity: Float!, $averagePrice: Float!, $investmentThesis: String, $exitStrategy: String) {\n  addToPortfolio(\n    ownerId: $ownerId\n    stockCode: $stockCode\n    quantity: $quantity\n    averagePrice: $averagePrice\n    investmentThesis: $investmentThesis\n    exitStrategy: $exitStrategy\n  ) {\n    id\n    name\n    items {\n      stock {\n        code\n      }\n      quantity\n      investmentThesis\n      exitStrategy\n    }\n  }\n}"): (typeof documents)["mutation AddToPortfolio($ownerId: String!, $stockCode: String!, $quantity: Float!, $averagePrice: Float!, $investmentThesis: String, $exitStrategy: String) {\n  addToPortfolio(\n    ownerId: $ownerId\n    stockCode: $stockCode\n    quantity: $quantity\n    averagePrice: $averagePrice\n    investmentThesis: $investmentThesis\n    exitStrategy: $exitStrategy\n  ) {\n    id\n    name\n    items {\n      stock {\n        code\n      }\n      quantity\n      investmentThesis\n      exitStrategy\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetMyPortfolio($ownerId: String!) {\n  myPortfolio(ownerId: $ownerId) {\n    id\n    name\n    items {\n      stock {\n        code\n        name\n        japaneseName\n        market\n        analysisResults {\n          stockPrice\n          status\n        }\n      }\n      quantity\n      averagePrice\n      currentValue\n      profitLoss\n      investmentThesis\n      exitStrategy\n    }\n    analysis {\n      totalValue\n      healthScore\n      diagnosisSummary\n      categoryExposure\n      tagExposure\n      narrativeAnalysis\n    }\n  }\n}"): (typeof documents)["query GetMyPortfolio($ownerId: String!) {\n  myPortfolio(ownerId: $ownerId) {\n    id\n    name\n    items {\n      stock {\n        code\n        name\n        japaneseName\n        market\n        analysisResults {\n          stockPrice\n          status\n        }\n      }\n      quantity\n      averagePrice\n      currentValue\n      profitLoss\n      investmentThesis\n      exitStrategy\n    }\n    analysis {\n      totalValue\n      healthScore\n      diagnosisSummary\n      categoryExposure\n      tagExposure\n      narrativeAnalysis\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetStockDetail($code: String!) {\n  stock(code: $code) {\n    code\n    name\n    japaneseName\n    market\n    japaneseMarket\n    sector17CodeName\n    description\n    analysisResults {\n      date\n      stockPrice\n      marketCap\n      status\n      aiSummary\n      riskLevel\n      riskDetails\n      state\n      expectationStructure\n      zScore\n      fScore\n      expectationGap\n      impliedRevenueGrowth\n      actualRevenueGrowth\n      tagSafetyShield\n      tagQualityGrowth\n      tagInstitutional\n      tagCashCow\n      tagSingleEngine\n      tagHighVolatility\n      tagSilentImprover\n      tagTurnaround\n      tagZombie\n      tagAccountingRisk\n      tagFragile\n      per\n      pbr\n      roe\n      roa\n      eps\n      bps\n      equityRatio\n      dividendYield\n      freeCashFlow\n    }\n    financials {\n      fiscalYear\n      quarter\n      periodEnd\n      revenue\n      operatingIncome\n      netIncome\n      operatingCf\n      investingCf\n      financingCf\n      totalAssets\n      totalEquity\n    }\n  }\n}"): (typeof documents)["query GetStockDetail($code: String!) {\n  stock(code: $code) {\n    code\n    name\n    japaneseName\n    market\n    japaneseMarket\n    sector17CodeName\n    description\n    analysisResults {\n      date\n      stockPrice\n      marketCap\n      status\n      aiSummary\n      riskLevel\n      riskDetails\n      state\n      expectationStructure\n      zScore\n      fScore\n      expectationGap\n      impliedRevenueGrowth\n      actualRevenueGrowth\n      tagSafetyShield\n      tagQualityGrowth\n      tagInstitutional\n      tagCashCow\n      tagSingleEngine\n      tagHighVolatility\n      tagSilentImprover\n      tagTurnaround\n      tagZombie\n      tagAccountingRisk\n      tagFragile\n      per\n      pbr\n      roe\n      roa\n      eps\n      bps\n      equityRatio\n      dividendYield\n      freeCashFlow\n    }\n    financials {\n      fiscalYear\n      quarter\n      periodEnd\n      revenue\n      operatingIncome\n      netIncome\n      operatingCf\n      investingCf\n      financingCf\n      totalAssets\n      totalEquity\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetStocks($search: String, $status: String, $rankingMode: String, $sector: String, $limit: Int, $offset: Int, $sortBy: String, $sortOrder: String) {\n  stocks(\n    search: $search\n    status: $status\n    rankingMode: $rankingMode\n    sector: $sector\n    limit: $limit\n    offset: $offset\n    sortBy: $sortBy\n    sortOrder: $sortOrder\n  ) {\n    code\n    name\n    japaneseName\n    market\n    japaneseMarket\n    sector17CodeName\n    analysisResults {\n      stockPrice\n      status\n      zScore\n      grossProfitability\n      expectationGap\n      per\n      pbr\n      dividendYield\n      roe\n      tagZombie\n      tagSafetyShield\n      tagQualityGrowth\n      tagInstitutional\n      tagCashCow\n      tagSingleEngine\n      tagSilentImprover\n      tagTurnaround\n      tagAccountingRisk\n      tagHighVolatility\n      tagFragile\n      fScore\n      actualRevenueGrowth\n      freeCashFlow\n      operatingCf\n      netIncome\n    }\n  }\n}"): (typeof documents)["query GetStocks($search: String, $status: String, $rankingMode: String, $sector: String, $limit: Int, $offset: Int, $sortBy: String, $sortOrder: String) {\n  stocks(\n    search: $search\n    status: $status\n    rankingMode: $rankingMode\n    sector: $sector\n    limit: $limit\n    offset: $offset\n    sortBy: $sortBy\n    sortOrder: $sortOrder\n  ) {\n    code\n    name\n    japaneseName\n    market\n    japaneseMarket\n    sector17CodeName\n    analysisResults {\n      stockPrice\n      status\n      zScore\n      grossProfitability\n      expectationGap\n      per\n      pbr\n      dividendYield\n      roe\n      tagZombie\n      tagSafetyShield\n      tagQualityGrowth\n      tagInstitutional\n      tagCashCow\n      tagSingleEngine\n      tagSilentImprover\n      tagTurnaround\n      tagAccountingRisk\n      tagHighVolatility\n      tagFragile\n      fScore\n      actualRevenueGrowth\n      freeCashFlow\n      operatingCf\n      netIncome\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation RemoveFromPortfolio($ownerId: String!, $stockCode: String!) {\n  removeFromPortfolio(ownerId: $ownerId, stockCode: $stockCode) {\n    id\n    analysis {\n      totalValue\n      healthScore\n      narrativeAnalysis\n      diagnosisSummary\n    }\n    items {\n      stock {\n        code\n      }\n    }\n  }\n}"): (typeof documents)["mutation RemoveFromPortfolio($ownerId: String!, $stockCode: String!) {\n  removeFromPortfolio(ownerId: $ownerId, stockCode: $stockCode) {\n    id\n    analysis {\n      totalValue\n      healthScore\n      narrativeAnalysis\n      diagnosisSummary\n    }\n    items {\n      stock {\n        code\n      }\n    }\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;