# Generated by Django 5.2.10 on 2026-04-29 08:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=256)),
                ('content_html', models.TextField(default='')),
                ('content_text', models.TextField(blank=True)),
                ('purpose', models.CharField(blank=True, choices=[('transactional', 'Transactional'), ('marketing', 'Marketing'), ('notification', 'Notification')], max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('dispatch_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('to', 'To'), ('cc', 'Cc'), ('bcc', 'Bcc'), ('from', 'From'), ('reply_to', 'Reply-To')], default='to', max_length=16)),
                ('address', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('batch_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='mailer.batchemail')),
            ],
        ),
        migrations.CreateModel(
            name='BatchEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256)),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('batch_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mailer.batchemail')),
            ],
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retry', 'Retry'), ('delivered', 'Delivered'), ('bounced', 'Bounced')], default='pending', max_length=32)),
                ('attempt_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('batch_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='mailer.batchemail')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentEmailStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('batch_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_status', to='mailer.batchemail')),
                ('email_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_status', to='mailer.emailrecord')),
            ],
        ),
    ]
